"""empty message

Revision ID: 3891356a13e
Revises: 564a7a3d46e6
Create Date: 2015-05-14 11:36:49.564000

"""

# revision identifiers, used by Alembic.
revision = '3891356a13e'
down_revision = '564a7a3d46e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
