"""empty message

Revision ID: 5507e890d562
Revises: 2c87c1ed9701
Create Date: 2015-05-18 12:18:39.152000

"""

# revision identifiers, used by Alembic.
revision = '5507e890d562'
down_revision = '2c87c1ed9701'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
